IDEM-106
dltxio/idem-mobile pull request #131
Opened 2022-06-15 04:35 UTC by JasminFarhi

2022-06-17 05:33 UTC, sbm-peter approved these changes

2022-06-17 05:50 UTC, jrocca82 submitted a review, later dismissed

2022-06-19 03:08 UTC, bitcoinbrisbane commented on app/src/utils/formatter.ts
> +    const year = Number(dateArray.slice(6, 10).join(""));
There is no need to do a split.  Use a .substring

2022-06-19 03:08 UTC, bitcoinbrisbane commented on app/src/utils/birthday-utils.ts
> +    const userAge = age.split("").slice(0, 2).join("");
Use a .substring

2022-06-19 03:09 UTC, bitcoinbrisbane requested changes
Don't convert to an array.

2022-06-19 05:32 UTC, bitcoinbrisbane commented on app/src/utils/birthday-utils.ts
> +    const userAge = age.split("").slice(0, 2).join("");
We also have a year of birth utils.  We could have used that to get the year of birth.

2022-06-19 05:48 UTC, bitcoinbrisbane commented on app/src/utils/birthday-utils.ts
> +    }
This method doesn't make sense.  We can use the functions of the moment.js lib to do all this for us.

2022-06-19 05:57 UTC, bitcoinbrisbane submitted a review, later dismissed
Use moment js instead of rolling your own!

2022-06-19 05:57 UTC, bitcoinbrisbane commented on app/src/utils/formatter.ts
> +    const year = Number(dateArray.slice(6, 10).join(""));
This method could be done by using moment to parse the date.  Then a .toString with the specific format required.

2022-06-20 00:09 UTC, xiangzhe0812 reviewed
Nice work, only two small stuff

2022-06-20 00:09 UTC, xiangzhe0812 commented on app/src/navigation/screens/ClaimScreen.tsx
> +                      console.log();
remove?

2022-06-20 00:09 UTC, xiangzhe0812 commented on app/src/navigation/screens/ClaimScreen.tsx
> +
lets put logic into hook please

2022-06-21 22:28 UTC, bitcoinbrisbane commented on app/src/hooks/useClaimScreen.ts
> +const useClaimScreen = (): Hooks => {
```suggestion
};

const useClaimScreen = (): Hooks => {
```

2022-06-21 22:31 UTC, bitcoinbrisbane approved these changes

2022-06-21 23:51 UTC, xiangzhe0812 approved these changes

2022-06-21 23:52 UTC, merged