IDEM-192
dltxio/idem-mobile pull request #194
Opened 2022-06-28 05:08 UTC by JasminFarhi

![Image from iOS (122)](https://user-images.githubusercontent.com/83386965/176097365-f836e2de-852b-4311-ad53-88262323a2a6.png)
![Image from iOS (123)](https://user-images.githubusercontent.com/83386965/176097370-3de4ed4e-5563-47a5-8240-ebad02715f60.png)

2022-06-28 22:37 UTC, bitcoinbrisbane requested changes
Seems to be a typo

2022-06-29 01:08 UTC, bitcoinbrisbane approved these changes

2022-06-29 01:10 UTC, bitcoinbrisbane requested changes
Need to check sonarqube

![image](https://user-images.githubusercontent.com/8411406/176329742-a436de25-e202-4455-8870-d58e0d541109.png)

2022-06-29 01:46 UTC, xiangzhe0812 commented on app/src/hooks/useVerifyClaims.tsx
> +    console.log(claim);
remove console.log

2022-06-29 01:49 UTC, xiangzhe0812 approved these changes

2022-06-29 05:18 UTC, amagon270 approved these changes

2022-06-29 05:19 UTC, merged