IDEM-193
dltxio/idem-mobile pull request #208
Opened 2022-06-29 11:23 UTC by xiangzhe0812

2022-06-29 11:47 UTC, xiangzhe0812 commented
Can ignore the sonar cloud security hotspots, I put basic auth password in the config file.

2022-06-29 23:36 UTC, bitcoinbrisbane commented on app/apis/Api.ts
> +  public gpibSingup = async (body: UserSignup) =>
```suggestion
  public gpibSignup = async (body: UserSignup) =>
```

2022-06-29 23:39 UTC, bitcoinbrisbane requested changes
Typo

2022-06-30 00:11 UTC, amagon270 submitted a review, later dismissed

2022-06-30 01:04 UTC, pondpiu commented on app/src/context/Exchange.tsx
> +        console.log(userInfo);
log

2022-06-30 02:20 UTC, pondpiu approved these changes
LGTM 🥔

2022-06-30 02:22 UTC, JasminFarhi approved these changes

2022-06-30 04:12 UTC, bitcoinbrisbane approved these changes

2022-06-30 04:13 UTC, merged