IDEM-11
dltxio/idem-mobile pull request #244
Opened 2022-07-13 02:41 UTC by pondpiu

#11 

- add import private key from file button
- check whether content start with and end with `KEY BLOCK` text
- show error alert when error is thrown

2022-07-13 06:17 UTC, bitcoinbrisbane reviewed
One minor thing the check, otherwise good work!

2022-07-13 06:17 UTC, bitcoinbrisbane commented on app/src/navigation/screens/PGPScreen.tsx
> +  });
Should that be ===

2022-07-14 01:07 UTC, JasminFarhi approved these changes

2022-07-14 01:13 UTC, bitcoinbrisbane commented on app/src/navigation/screens/PGPScreen.tsx
> +        "Error",
As discussed, lets make a constants or enum for these...

2022-07-14 01:13 UTC, bitcoinbrisbane commented on app/src/navigation/screens/PGPScreen.tsx
> +        `Fail to extract private key from file \n> ${
```suggestion
        `Failed to extract the private key from file \n> ${
```

2022-07-14 01:14 UTC, bitcoinbrisbane requested changes
Few things

2022-07-14 01:52 UTC, bitcoinbrisbane commented on app/src/hooks/usePpg.ts
> +        `There was a problem generating your public Key.\n > ${error.message}`
```suggestion
        `There was a problem generating your public key.\n > ${error.message}`
```

2022-07-14 01:53 UTC, bitcoinbrisbane approved these changes
Good work!  Good gardening too.

2022-07-14 01:55 UTC, JasminFarhi approved these changes

2022-07-14 01:55 UTC, merged