IDEM-245
dltxio/idem-mobile pull request #289
Opened 2022-07-22 06:10 UTC by pondpiu

#245 
Verify otp screen

![Image from iOS](https://user-images.githubusercontent.com/1115763/180995157-46eb5008-b453-46ea-98ca-8ae5ccf795a5.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/1115763/180995175-2e3c9948-a12c-4f51-bc13-64d556fa4f52.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/1115763/180995181-efb01105-225a-414f-b209-88edc8ad9339.png)

Waiting for proxy endpoint to be implemented

2022-07-25 10:03 UTC, bitcoinbrisbane reviewed
Looks good, just need a few screen shots @pondpiu

2022-07-26 01:20 UTC, brettvniekerk commented on app/src/navigation/screens/ClaimScreen.tsx
> +            disabled={!canSave}
So is it disabled if the user canSave? Double negative hard to understand

2022-07-26 01:22 UTC, brettvniekerk approved these changes

2022-07-26 01:34 UTC, bitcoinbrisbane commented
Need to address the 2 sonarqube issues too

2022-07-26 01:36 UTC, brettvniekerk commented on app/src/navigation/screens/ClaimScreen.tsx
> +            disabled={!canSave}
So is it disabled if the user canSave? Double negative hard to understand

2022-07-26 01:36 UTC, brettvniekerk commented on app/src/navigation/screens/ClaimScreen.tsx
> +            disabled={!canSave}
Same here

2022-07-26 01:37 UTC, brettvniekerk commented on app/src/navigation/screens/ClaimScreen.tsx
> +            disabled={!canSave}
So is it disabled if the user canSave? Double negative hard to understand

2022-07-26 01:37 UTC, brettvniekerk requested changes

2022-07-26 01:37 UTC, brettvniekerk commented on app/src/navigation/screens/ClaimScreen.tsx
> +            disabled={!canSave}
So is it disabled if the user canSave? Double negative hard to understand

2022-07-26 01:37 UTC, brettvniekerk commented on app/src/navigation/screens/ClaimScreen.tsx
> +            disabled={!canSave}
Same here

2022-07-26 11:36 UTC, xiangzhe0812 commented
@pondpiu removed verify otp screen, instead using Alert.prompt to input verification code

2022-07-26 23:14 UTC, brettvniekerk submitted a review, later dismissed

2022-07-26 23:14 UTC, brettvniekerk commented on app/src/context/ClaimsStore.tsx
> +    value: any,
Can you avoid any type?

2022-07-27 01:36 UTC, bitcoinbrisbane submitted a review, later dismissed

2022-07-27 02:42 UTC, xiangzhe0812 submitted a review, later dismissed

2022-07-27 04:37 UTC, bitcoinbrisbane approved these changes

2022-07-27 04:37 UTC, xiangzhe0812 approved these changes

2022-07-27 04:41 UTC, merged